### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by sota0121** [sota0121/minitube#1]
# Implementation Roadmap

## Features of MVP

- == Ph1 ==
- Upload Movies - Ph1
- List Movies - Ph1
- Play Movies - Ph1
- == Ph2 ==
- Search Movies - Ph2
- == Ph3 ==
- Users management - Ph3

## Plan of Phase 1

- [ ] Data Architecture
  - [x] prototype ERD
- [ ] Build base dev infra
  - [ ] WebApp ( flask , react ) container
  - [ ] RDB ( postgresql ) container
  - [ ] make Bucket on Cloud Storage
  - [ ] connect to bucket
- STEP 1 : base web application
  - [ ] single page webapp with flask : hello world
  - [ ] connect to database
  - [ ] create model
  - [ ] simple CRUD
- STEP 2 : play the movie of files in server local storage
  - [ ] set testing movie file in flask container
  - [ ] render html to play the movie
- STEP 3 : play the movie of files in Cloud Storage
  - [ ] set testing movie file in Cloud Storage Bucket
  - [ ] load the movie file from Cloud Storage with Cloud Storage Client Library
- STEP 4 : Using DataBase ( movies only / users, channels have testing data )
  - [ ] get the movie file path from DataBase
  - [ ] Upload Movie File to Cloud Storage and register info to db
- STEP 5 : ( considering ... )

## Reference

[My Notion - Youtube みたいなアプリをつくる](https://www.notion.so/YouTube-f72ed7320a7f428eb53ea8e6c14dd5aa)
